buildscript {
	repositories {
		maven {
			name = "Fabric"
			url = "https://maven.fabricmc.net/"
		}
		mavenCentral()
	}
	dependencies {
		classpath "net.fabricmc:fabric-loom:1.15"
	}
}

apply plugin: "net.fabricmc.fabric-loom"
apply plugin: "maven-publish"

base {
	archivesName = "${project.mod_id}-mc${project.minecraft_version_26_x}"
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version_26_x}"
	mappings loom.officialMojangMappings()

	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version_26_x}"
}

loom {
	mods {
		"${project.mod_id}" {
			sourceSet sourceSets.main
		}
	}
}

processResources {
	inputs.property "version", project.version
	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}
