org.gradle.jvmargs=-Xmx2G -Djava.net.preferIPv4Stack=true
org.gradle.parallel=true
systemProp.java.net.preferIPv4Stack=true
systemProp.java.net.preferIPv6Addresses=false

mod_id=local_skin_changer
mod_name=Local Skin Changer
mod_version=1.0.0
maven_group=com.duckii.localskinchanger

loader_version=0.18.5

minecraft_version_1_20_4=1.20.4
yarn_mappings_1_20_4=1.20.4+build.3
fabric_api_version_1_20_4=0.97.2+1.20.4

minecraft_version_1_21_x=1.21.6
yarn_mappings_1_21_x=1.21.6+build.1
fabric_api_version_1_21_x=0.127.1+1.21.6

minecraft_version_26_x=26.1.2
fabric_api_version_26_x=0.145.4+26.1.2
